
import random    

temas = [
    "O impacto das redes sociais na sociedade contemporânea.",
    "A importância da educação ambiental para o futuro do planeta.",
    "Os desafios e benefícios do trabalho remoto.",
    "A influência da tecnologia na comunicação interpessoal.",
    "A desigualdade social e suas consequências na vida urbana.",
    "O papel da mídia na formação da opinião pública.",
    "A valorização da cultura local em um mundo globalizado.",
    "Os efeitos do consumo excessivo na saúde mental.",
    "A importância do esporte na promoção da inclusão social.",
    "O desafio da mobilidade urbana nas grandes cidades.",
    "O direito de votar e a participação cidadã na sociedade brasileira.",
    "O trabalho infantil e seus impactos no desenvolvimento social.",
    "A convivência com as diferenças e a promoção da tolerância.",
    "A ética e os desafios do comportamento individual na sociedade.",
    "O papel do trabalho na construção da dignidade humana.",
    "Direitos da criança e do adolescente no Brasil.",
    "Cidadania e participação social no século XXI.",
    "A transformação social por meio da educação.",
    "A persistência da violência contra a mulher na sociedade brasileira.",
    "O desafio da inclusão digital e o acesso à informação.",
    "A manipulação do comportamento do usuário pelo controle de dados na internet.",
    "A democratização do acesso à cultura no Brasil.",
    "Os efeitos da publicidade infantil na formação das crianças.",
    "O impacto das redes sociais na política e na opinião pública.",
    "A influência da tecnologia na vida acadêmica dos jovens.",
    "O consumo consciente e a preservação ambiental.",
    "A mobilidade urbana e seus desafios para as grandes cidades.",
    "O papel da escola na formação de cidadãos críticos.",
    "O direito à saúde mental e sua importância na sociedade.",
    "A valorização da cultura regional em um contexto global.",
    "O impacto da tecnologia na comunicação interpessoal.",
    "A desigualdade social e suas consequências na vida urbana.",
    "O trabalho remoto e seus desafios para a produtividade.",
    "A importância do esporte na promoção da inclusão social.",
    "O papel da mídia na formação da opinião pública.",
    "A ética na sociedade contemporânea.",
    "O impacto da educação ambiental no futuro do planeta.",
    "A preservação ambiental e o desenvolvimento sustentável.",
    "A inclusão social de pessoas com deficiência.",
    "A violência urbana e suas consequências sociais.",
    "O acesso à educação de qualidade como direito universal.",
    "O impacto da imigração na sociedade brasileira.",
    "A importância da leitura na formação cidadã.",
    "O desafio de combater o racismo estrutural no Brasil.",
    "O papel do jovem na transformação social.",
    "A educação sexual nas escolas brasileiras.",
    "O impacto das fake news na sociedade contemporânea.",
    "A importância da ciência e da tecnologia para o desenvolvimento.",
    "O direito à liberdade de expressão na era digital.",
    "A valorização da diversidade cultural no Brasil.",
    "O desafio da sustentabilidade nos centros urbanos.",
    "A educação inclusiva como ferramenta de igualdade social.",
    "O papel da família na formação ética e moral dos jovens.",
    "A promoção da saúde e bem-estar na sociedade.",
    "O combate à discriminação e à intolerância religiosa.",
    "O impacto do bullying na vida de crianças e adolescentes.",
    "A importância do voluntariado e da solidariedade.",
    "O acesso à informação e à tecnologia como direito social.",
    "O papel do cinema e da arte na formação cultural.",
    "A proteção dos direitos humanos no Brasil.",
    "A ética e a responsabilidade nas redes sociais.",
    "O impacto das mudanças climáticas no cotidiano das pessoas.",
    "A educação financeira como ferramenta de cidadania.",
    "O desenvolvimento sustentável e suas práticas no Brasil.",
    "O combate à pobreza e à desigualdade social.",
    "A importância do pensamento crítico na sociedade.",
    "O acesso à cultura digital e aos meios de comunicação.",
    "A valorização da memória histórica e cultural do país.",
    "A influência da tecnologia na educação à distância.",
    "O papel da educação no combate à violência urbana.",
    "A promoção da igualdade de gênero na sociedade.",
    "O impacto das drogas na vida de jovens e famílias.",
    "O acesso à saúde pública e seus desafios.",
    "A preservação da fauna e flora brasileiras.",
    "O desafio da mobilidade urbana sustentável.",
    "A importância da leitura e da escrita na educação.",
    "A ética profissional e seus impactos sociais.",
    "O impacto do trabalho infantil na educação.",
    "O papel das organizações não governamentais na sociedade.",
    "A inclusão social por meio do esporte.",
    "O impacto da tecnologia na comunicação entre gerações.",
    "A promoção da cultura local em um mundo globalizado.",
    "O desafio do consumo consciente na sociedade moderna.",
    "A importância da participação política dos jovens.",
    "O combate à violência doméstica no Brasil.",
    "A sustentabilidade ambiental e o futuro do planeta.",
    "O acesso à educação de qualidade para todos.",
    "A valorização da diversidade cultural nas escolas.",
    "O impacto da globalização na cultura brasileira.",
    "A importância da preservação do patrimônio histórico.",
    "O papel da escola na construção da cidadania.",
    "O direito à liberdade de expressão e seus limites.",
    "O impacto da tecnologia na saúde e bem-estar.",
    "A promoção da igualdade racial na sociedade.",
    "O combate à exploração do trabalho infantil.",
    "A educação ambiental como ferramenta de transformação social.",
    "O papel da arte e da cultura na formação cidadã.",
    "A ética e a responsabilidade no uso das redes sociais.",
    "O acesso à informação como direito de todos.",
    "O combate à violência nas escolas brasileiras.",
    "A importância da ciência e da tecnologia na sociedade.",
    "O impacto do consumo excessivo na sociedade.",
    "A inclusão social e o respeito às diferenças.",
    "O papel do esporte na formação ética e social.",
    "A preservação dos recursos naturais e a sustentabilidade.",
    "O impacto da urbanização no meio ambiente.",
    "A valorização da cultura popular brasileira.",
    "O acesso à educação como direito fundamental.",
    "O combate à desigualdade social e econômica.",
    "A importância da leitura para a cidadania.",
    "O impacto da tecnologia na educação e no trabalho.",
    "O papel da família na formação ética dos jovens.",
    "A promoção da saúde e da qualidade de vida.",
    "O combate à discriminação e ao preconceito.",
    "A educação como ferramenta de inclusão social.",
    "O desafio da mobilidade urbana e da sustentabilidade.",
    "O papel da ética na sociedade contemporânea.",
    "O impacto das redes sociais na vida dos jovens.",
    "A preservação ambiental e a responsabilidade social."
]

while temas:  
    input("Aperte Enter para escolher uma redação...")
    escolhido = random.choice(temas)


    print("escolhido")
    temas.remove(escolhido)  

print("Todos os temas já foram escolhidos! (o cara ficou apertando enter por umas 100 vezes vsfd D: )")